// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function GetApplicationConfigContext():Promise<config.ApplicationConfigContext>;

export function GetBeans():Promise<Array<any>>;

export function GetCtx():Promise<context.Context>;

export function Greet(arg1:string):Promise<string>;
