// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplicationConfigContext() {
  return window['go']['backend']['App']['GetApplicationConfigContext']();
}

export function GetBeans() {
  return window['go']['backend']['App']['GetBeans']();
}

export function GetCtx() {
  return window['go']['backend']['App']['GetCtx']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}
