// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entry} from '../models';

export function DeleteContentByPrimary(arg1:string):Promise<void>;

export function QueryAllContent():Promise<Array<entry.Content>>;

export function QueryContentByCondition(arg1:entry.ContentController):Promise<Array<entry.Content>>;

export function QueryContentByType(arg1:number):Promise<Array<entry.Content>>;

export function QueryContentByValue(arg1:string):Promise<Array<entry.Content>>;
