// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContentByPrimary(arg1) {
  return window['go']['controller']['ContentController']['DeleteContentByPrimary'](arg1);
}

export function QueryAllContent() {
  return window['go']['controller']['ContentController']['QueryAllContent']();
}

export function QueryContentByCondition(arg1) {
  return window['go']['controller']['ContentController']['QueryContentByCondition'](arg1);
}

export function QueryContentByType(arg1) {
  return window['go']['controller']['ContentController']['QueryContentByType'](arg1);
}

export function QueryContentByValue(arg1) {
  return window['go']['controller']['ContentController']['QueryContentByValue'](arg1);
}
