// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entry} from '../models';

export function QueryAllValueTypeEnum():Promise<Array<entry.EnumValue>>;
